node:
  - name: node0
    ip: http://13.124.245.223:9080
  - name: node1
    ip: http://13.209.181.185:9080
  - name: node2
    ip: http://13.209.175.30:9080
  - name: node3
    ip: http://13.209.210.144:9080

channel:
  - name: "1"
    nodes: [node0, node1, node2, node3]
  - name: "2"
    nodes: [node0, node1, node2, node3]
  - name: "3"
    nodes: [node0, node1, node2, node3]
  - name: "4"
    nodes: [node0, node1, node2, node3]

prometheus:
  prometheusExternal: http://52.79.176.139:9090
  prometheusISAAC: http://52.79.176.139:9090
  queryPath: /api/v1/query
  crawlingInterval: 5
  nodeType: goloop     # Can be used Node type (loopchain, goloop)
  jobNameOfgoloop: goloop  # If using the goloop, should set the job name of prometheus.

blockchain:
  crawlingInterval: 10
  db:
    - type: sqlite3
      id: ""
      pass: ""
      database: ""    # For remote MySQL server, use tcp($SERVER_IP:3306):$DB_NAME.
      path: data/crawling_data.db

etc:
  sessionTimeout: 30
  language: ko
  loglevel: 1
  db:
    - type: sqlite3
      id: ""
      pass: ""
      database: ""
      path: data/isaac.db
  loginLogoImagePath: images/iconloop.png

authorization:
  thirdPartyUserAPI: [channels]            # Can be used API list is channels, nodes, blocks, txs.