node:
  - name: node0
    ip: http://13.125.120.242:9080
  - name: node1
    ip: http://15.164.163.252:9080
  - name: node2
    ip: http://13.209.77.121:9080
  - name: node3
    ip: http://13.125.244.31:9080

channel:
  - name: "5d46aa"
    nodes: [node0, node1, node2, node3]
  - name: "822027"
    nodes: [node0, node1, node2, node3]
  - name: "2b127a"
    nodes: [node0, node1, node2, node3]

prometheus:
  prometheusExternal: http://13.125.120.242:9090
  prometheusISAAC: http://13.125.120.242:9090
  queryPath: /api/v1/query
  crawlingInterval: 5
  nodeType: goloop     # Can be used Node type (loopchain, goloop)
  jobNameOfgoloop: goloop  # If using the goloop, should set the job name of prometheus.

blockchain:
  crawlingInterval: 10
  db:
    - type: sqlite3
      id: ""
      pass: ""
      database: ""    # For remote MySQL server, use tcp($SERVER_IP:3306):$DB_NAME.
      path: data/crawling_data.db

etc:
  sessionTimeout: 30
  language: ko
  loglevel: 1
  db:
    - type: sqlite3
      id: ""
      pass: ""
      database: ""
      path: data/isaac.db
  loginLogoImagePath: images/iconloop.png

authorization:
  thirdPartyUserAPI: [channels]            # Can be used API list is channels, nodes, blocks, txs.