node:
  - name: node1
    ip: http://13.233.143.129:9000
  - name: node2
    ip: http://13.232.66.215:9000
  - name: node3
    ip: http://13.127.195.119:9000
  - name: node4
    ip: http://35.154.172.101:9000

channel:
  - name: "channel1"
    nodes: [node1, node2, node3, node4]
  - name: "channel2"
    nodes: [node1, node2, node3, node4]

prometheus:
  prometheus: http://prometheus:9090
  queryPath: /api/v1/query
  crawlingInterval: 2

blockchain:
  crawlingInterval: 10
  db:
    - type: sqlite3
      id: ""
      pass: ""
      database: ""
      path: data/crawling_data.db

etc:
  sessionTimeout: 30
  language: ko
  loglevel: 1
  db:
    - type: sqlite3
      id: ""
      pass: ""
      database: ""
      path: data/isaac.db
